services:
  postgres:
    image: postgres:16
    container_name: antifraud-postgres
    networks:
      - kafka-net
    environment:
      POSTGRES_DB: antifraud
      POSTGRES_USER: antifraud
      POSTGRES_PASSWORD: antifraud
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U antifraud -d antifraud"]
      interval: 5s
      timeout: 5s
      retries: 20

  db-init:
    image: postgres:16
    networks:
      - kafka-net
    depends_on:
      - postgres
    environment:
      PGPASSWORD: antifraud
    entrypoint: >
      bash -c "
      until pg_isready -h postgres -p 5432; do sleep 2; done &&
      psql -h postgres -U antifraud -d antifraud -c \"
      INSERT INTO fraud_rules(id, code,title,description,threshold,enabled,severity,created_at)
      VALUES
      (1, 'HIGH_AMOUNT','High amount','Amount > threshold',10000,1,'HIGH', NOW()),
      (2, 'VELOCITY','Velocity','More than threshold tx within 2 minutes (threshold=N)',5,1,'MEDIUM', NOW()),
      (3, 'GEO_JUMP','Geo jump','Country changed within 60 seconds (threshold=seconds)',60,1,'MEDIUM', NOW())
      ON CONFLICT (code) DO NOTHING;
      \"
      "
    restart: "no"

  kafka-1:
    image: public.ecr.aws/bitnami/kafka:3.7.1
    container_name: kafka-1
    hostname: kafka-1
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT

      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093

      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka1_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL","kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 30

  kafka-2:
    image: public.ecr.aws/bitnami/kafka:3.7.1
    container_name: kafka-2
    hostname: kafka-2
    networks:
      - kafka-net
    ports:
      - "9093:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT

      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093

      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka2_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL","kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 30

  kafka-init:
    image: public.ecr.aws/bitnami/kafka:3.7.1
    container_name: kafka-init
    networks:
      - kafka-net
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    entrypoint: /bin/bash
    command: -c "
      kafka-topics.sh \
      --bootstrap-server kafka-1:9092 \
      --create \
      --if-not-exists \
      --topic transactions \
      --partitions 2 \
      --replication-factor 2
     "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - kafka-net
    ports:
      - "8089:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092
    depends_on:
      - kafka-1
      - kafka-2

  antifraud-api:
    build: services/antifraud-api
    container_name: antifraud-api
    networks:
      - kafka-net
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=antifraud
      - DB_USER=antifraud
      - DB_PASS=antifraud

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092
    depends_on:
      postgres:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy


  tx-generator:
    build: services/tx-generator
    container_name: tx-generator
    networks:
      - kafka-net
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092
      - TOPIC=transactions
      - RATE_PER_SEC=30
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: antifraud-prometheus
    networks:
      - kafka-net
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - antifraud-api

  grafana:
    image: grafana/grafana:11.2.2
    container_name: antifraud-grafana
    networks:
      - kafka-net
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  redis:
    image: redis:7
    container_name: antifraud-redis
    networks:
      - kafka-net
    ports:
      - "6379:6379"

  superset:
    image: apache/superset:4.0.2
    container_name: antifraud-superset
    networks:
      - kafka-net
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=dev_secret_key_change_me
    volumes:
      - ./dashboards/superset:/app/superset_home
    depends_on:
      - redis
      - postgres
    command: >
      /bin/bash -lc "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@local --password admin || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "

  airflow-db:
    image: postgres:16
    container_name: airflow-db
    networks:
      - kafka-net
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - airflow_db:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.10.4
    container_name: antifraud-airflow
    networks:
      - kafka-net
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8081:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    command: >
      bash -c "airflow scheduler & airflow webserver"

  airflow-init:
    image: apache/airflow:2.10.4
    container_name: airflow-init
    networks:
      - kafka-net
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    entrypoint: /bin/bash
    command: -c "
      airflow db migrate &&
      airflow users create \
      --username airflow \
      --password airflow \
      --firstname Air \
      --lastname Flow \
      --role Admin \
      --email airflow@local || true
     "
volumes:
  pg_data:
  kafka1_data:
  kafka2_data:
  airflow_db:

networks:
  kafka-net: